---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetPool
metadata:
  name: east-west
  namespace: cats
spec:
  ip_version: 4
  min_prefix: 19
  max_prefix: 24
  prefixes:
    - 10.109.0.0/16
  tags:
    - east-west
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: cats-mgmt-net
  namespace: cats
spec:
  vpc: cats
  type: l2vpn
  vlan:
    id: "10"
  dnsServers:
    - "4.2.2.1"
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: cats-ew-net-rail-0
  namespace: cats
spec:
  vpc: cats-ew
  type: l3vpn
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: cats-ew-subnet-rail-0
  namespace: cats
spec:
  prefix_length: 24
  subnetpool: east-west
  subnet: cats-ew-subnet-rail-0
  vpc: cats-ew
  network: cats-ew-net-rail-0
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: cats-ew-net-rail-1
  namespace: cats
spec:
  vpc: cats-ew
  type: l3vpn
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: cats-ew-subnet-rail-1
  namespace: cats
spec:
  prefix_length: 24
  subnetpool: east-west
  subnet: cats-ew-subnet-rail-1
  vpc: cats-ew
  network: cats-ew-net-rail-1
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: cats-ew-net-rail-2
  namespace: cats
spec:
  vpc: cats-ew
  type: l3vpn
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: cats-ew-subnet-rail-2
  namespace: cats
spec:
  prefix_length: 24
  subnetpool: east-west
  subnet: cats-ew-subnet-rail-2
  vpc: cats-ew
  network: cats-ew-net-rail-2
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: cats-ew-net-rail-3
  namespace: cats
spec:
  vpc: cats-ew
  type: l3vpn
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: cats-ew-subnet-rail-3
  namespace: cats
spec:
  prefix_length: 24
  subnetpool: east-west
  subnet: cats-ew-subnet-rail-3
  vpc: cats-ew
  network: cats-ew-net-rail-3
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: cats-mgmt-subnet
  namespace: cats
spec:
  prefix_length: 24
  subnetpool: default
  subnet: cats-mgmt-subnet
  vpc: cats
  network: cats-mgmt-net
  gateway: true
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: cats-public-subnet
  namespace: cats
spec:
  prefix_length: 28
  subnetpool: public
  subnet: cats-public-subnet
  vpc: cats
  network: cats-mgmt-net
  gateway: true
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: NetworkBundle
metadata:
  name: cats
  namespace: cats
spec:
  clusterName: cats-cluster
  networkv2:
    ethernets:
      eth1:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_mgmt_0_mac
        mtu: 1500
        addresses:
         - ipFromSubnet:
             name: cats-mgmt-subnet
        gatewayv4:
          gatewayFromSubnet:
            name: cats-mgmt-subnet
        nameservers:
          addresses:
            dnsFromNetwork:
              name: cats-mgmt-net
      eth2:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_mgmt_1_mac
        mtu: 1500
        addresses:
         - ipFromSubnet:
             name: cats-ew-subnet-rail-0
        routes:
         - to:
             cidrFromSubnet:
               name: cats-ew-subnet-rail-0
           via:
             gatewayFromSubnet:
               name: cats-ew-subnet-rail-0
      eth3:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_data_0_mac
        addresses:
         - ipFromSubnet:
             name: cats-ew-subnet-rail-1
        routes:
         - to:
             cidrFromSubnet:
               name: cats-ew-subnet-rail-1
           via:
             gatewayFromSubnet:
               name: cats-ew-subnet-rail-1
        mtu: 1500
      eth4:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_data_1_mac
        mtu: 1500
        addresses:
         - ipFromSubnet:
             name: cats-ew-subnet-rail-3
        routes:
         - to:
             cidrFromSubnet:
               name: cats-ew-subnet-rail-3
           via:
             gatewayFromSubnet:
               name: cats-ew-subnet-rail-3
