all:
  hosts:
    localhost:
      sdn_provider: verity
      ufo_fabric_backend: 'verity'
      br_mgmt_phys_interface: ens5
      switch_port_name_prefix: "eth1/"

      verity_operator_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/verity-operator
      verity_operator_chart_version: 0.0.1-6b71b38
      verity_operator_image_tag: 0.0.1-6b71b38.1774347742
