all:
  hosts:
    localhost:
      sdn_provider: verity
      ufo_fabric_backend: 'verity'
      br_mgmt_phys_interface: ens5
      br_ext_phys_interface: ens6
      switch_port_name_prefix: "eth1/"

      management_base_switch: "10.200.0"

      verity_operator_chart_repo: oci://registry.ci.mirantis.com/k0rdent-bm/charts/verity-operator
      verity_operator_chart_version: 0.0.1-6b71b38
      verity_operator_image_tag: 0.0.1-6b71b38.1774347742


      frr:
        enabled: true
        bgp:
          listen_interface: 'ens6'
          enabled: true
          router_id: 192.168.100.1
          asn: 64513
          sdn:
            asn: 64512
            peer_ranges:
            - 192.168.100.0/24
