apiVersion: nico.mirantis.com/v1alpha1
kind: InstanceType
metadata:
  name: gpu-a100
  namespace: platform-admin
spec:
  description: A100 nodes
  machineIds:
    - bySerialNumber: "DPG5NS621A0000"
    - bySerialNumber: "DPG5NS621A0001"
    - bySerialNumber: "DPG5NS621A0002"
---
apiVersion: nico.mirantis.com/v1alpha1
kind: InstanceTypeAllocation
metadata:
  name: gpu-platform-adminlloc
  namespace: platform-admin
spec:
  instanceTypeRef:
    name: gpu-a100
  reservedMachineCount: 3
