apiVersion: k0rdent.mirantis.com/v1beta1
kind: Management
metadata:
  labels:
    k0rdent.mirantis.com/component: kcm
  name: kcm
spec:
  core:
    capi: {}
    kcm:
      config:
        regional:
          telemetry:
            mode: disabled
          velero:
            enabled: false
  providers:
  - name: cluster-api-provider-k0sproject-k0smotron
  - name: cluster-api-provider-ipam
  - name: cluster-api-provider-infoblox
  - name: projectsveltos
{% if nico_capi_provider_enabled | bool %}
  - config:
      manager:
        image:
          repository: {{ nico_capi_provider_image }}
          tag: {{ nico_capi_provider_image_tag }}
      nicoClient:
        insecureSkipTLSVerify: true
    name: cluster-api-provider-nico
    template: cluster-api-provider-nico-{{ nico_capi_provider_chart_version }}
{% endif %}
  release: kcm-1-11-0
