apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-nico-{{ nico_capi_provider_chart_version }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-nico
      version: {{ nico_capi_provider_chart_version }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-capm3-ci-repo
  providers:
    - infrastructure-nico
  capiContracts:
    v1beta2: v1beta2
