backends:
  fabric_default: {{ ufo_fabric_backend }}
  fabric:
    noop:
      enabled: false
      driver: noop
    netris:
      enabled: {{ 'true' if ufo_fabric_backend == 'netris' else 'false' }}
      driver: netris
      config:
        defaultTenant: Admin
        defaultSites:
          - default
    verity:
      enabled: {{ 'true' if ufo_fabric_backend == 'verity' else 'false' }}
      driver: verity
    verity-ewf:
      enabled: {{ 'true' if ufo_fabric_backend == 'verity' else 'false' }}
      driver: verity
      config:
        site: ewf
        fabric_type: "Spectrum-X 2 Tier"
    nico:
      enabled: {{ 'true' if nico_enabled else 'false' }}
      driver: nico
  provision_default: {{ 'nico' if nico_enabled else 'metal3' }}
  provision:
    metal3:
      driver: metal3
      enabled: {{ 'false' if nico_enabled else 'true' }}
    nico:
      enabled: {{ 'true' if nico_enabled else 'false' }}
      driver: nico
