! FRR configuration — Ansible template (templates/frr/frr.conf)
! Set daemons in /etc/frr/daemons to match (e.g. zebra=yes; add bgpd, ospfd, etc.).

frr version 8
frr defaults traditional
hostname {{ frr.hostname | default(inventory_hostname) }}
log syslog {{ frr.log_level | default('informational') }}
service integrated-vtysh-config
!
{% if frr.bgp.enabled %}
router bgp  {{ frr.bgp.asn }}
 bgp router-id {{ frr.bgp.router_id | default('127.0.0.1') }}
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp cluster-id {{ frr.bgp.router_id | default('127.0.0.1') }}
 coalesce-time 1000
 neighbor k8s peer-group
 neighbor k8s capability extended-nexthop
 neighbor k8s remote-as {{ frr.bgp.sdn.asn }}
 neighbor k8s update-source {{ hostvars[inventory_hostname]['ansible_' + frr.bgp.listen_interface]['ipv4']['address'] }}
 {% for peer_range in frr.bgp.sdn.peer_ranges -%}
 bgp listen range {{ peer_range }} peer-group k8s
 {% endfor -%}
 !
 address-family ipv4 unicast
   neighbor k8s activate
 exit-address-family
 !
{% endif -%}
!
line vty
!
