---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: dogs-mgmt-net
  namespace: dogs
spec:
  vpc: dogs
  type: l2vpn
  vlan:
    id: "10"
  dnsServers:
    - "4.2.2.1"
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: dogs-mgmt-subnet
  namespace: dogs
spec:
  prefix_length: 24
  subnetpool: default
  subnet: dogs-mgmt-subnet
  vpc: dogs
  network: dogs-mgmt-net
  gateway: true
---
 apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: dogs-data-net
  namespace: dogs
spec:
  vpc: dogs
  type: l2vpn
  vlan:
    id: "11"
  dnsServers:
    - "4.2.2.1"
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: dogs-data-subnet
  namespace: dogs
spec:
  prefix_length: 24
  subnetpool: default
  subnet: dogs-data-subnet
  vpc: dogs
  network: dogs-data-net
  gateway: true
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: NetworkBundle
metadata:
  name: dogs
  namespace: dogs
spec:
  clusterName: dogs-cluster
  networkv2:
    ethernets:
      eth1:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_mgmt_0_mac
        mtu: 1500
      eth2:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_mgmt_1_mac
        mtu: 1500
      eth3:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_data_0_mac
        mtu: 1500
      eth4:
        match:
          macAddress:
            fromAnnotation:
              object: machine
              annotation: net_interface_data_1_mac
        mtu: 1500
    bonds:
      bond0:
       parameters:
         mode: active-backup
       interfaces:
        - eth1
        - eth2
       addresses:
        - ipFromSubnet:
            name: dogs-mgmt-subnet
       gatewayv4:
         gatewayFromSubnet:
           name: dogs-mgmt-subnet
       mtu: 1500
       nameservers:
         addresses:
           dnsFromNetwork:
             name: dogs-mgmt-net
      bond1:
       parameters:
         mode: active-backup
       interfaces:
        - eth3
        - eth4
       mtu: 1500
    vlans:
      data:
        id:
          vlanIdFromNetwork:
            name: dogs-data-net
        link: bond1
        addresses:
         - ipFromSubnet:
             name: dogs-data-subnet
        mtu: 1500
