---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Vpc
metadata:
  annotations:
    ufo.mirantis.com/netris-adminTenant: "Admin"
  name: internet
  namespace: kcm-system
spec: {}
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: VpcPeeringPolicy
metadata:
  name: allow-from-everyone
  namespace: kcm-system
spec:
  local_vpc:
    name: internet
  allowed_vpcs:
    - vpcName: '*'
      vpcNamespace: cats
    - vpcName: '*'
      vpcNamespace: dogs
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: VpcPeering
metadata:
  name: internet-to-cats
  namespace: kcm-system
spec:
  local:
    name: internet
  remote:
    name: cats
    namespace: cats
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: VpcPeering
metadata:
  name: internet-to-dogs
  namespace: kcm-system
spec:
  local:
    name: internet
  remote:
    name: dogs
    namespace: dogs
