- name: Setup networking
  hosts: "all"
  gather_facts: true
  become: true

  vars_files:
    - ./vars/common.yml
    - ./vars/{{ sdn_provider }}.yml

  tasks:
    # Create PXE network
    # ===========================================
    - name: Create PXE network
      include_tasks: tasks/network.yml


  handlers:
  - name: Restart nftables
    ansible.builtin.service:
      name: nftables
      state: restarted
