apiVersion: nico.mirantis.com/v1alpha1
kind: OperatingSystem
metadata:
  name: ubuntu-22.04
spec:
  description: Ubuntu 22.04 via iPXE
  ipxeScript: |
    #!ipxe
    kernel ...
  userData: |
    #cloud-config
    ...
