# NetworkBundle for NICO backend.
apiVersion: ufo.mirantis.com/v1alpha1
kind: NetworkBundle
metadata:
  name: tenant-a-networkbundle
  namespace: tenant-a
spec:
  clusterName: tenant-a-cluster
  networkv2:
    ethernets:
      enp1s0:
        dhcp4: true
        connectToNetwork:
          name: ns-network
            eth-ew0:
        match:
          fabricLocation:
            railId: 0
        addresses:
          - ipFromSubnet:
              name: ew-subnet
      eth-ew1:
        match:
          fabricLocation:
            railId: 1
        addresses:
          - ipFromSubnet:
              name: ew-subnet
      eth-ew2:
        match:
          fabricLocation:
            railId: 2
        addresses:
          - ipFromSubnet:
              name: ew-subnet
      eth-ew3:
        match:
          fabricLocation:
            railId: 3
        addresses:
          - ipFromSubnet:
              name: ew-subnet
    nvlinks:
      nvlink1:
        connectToNetwork:
          name: nvlink-partition
