# Ethernet network
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: ns-network
  namespace: tenant-a
spec:
  vpc: tenant-a
  type: l3vpn
---
# Ethernet network
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: public-network
  namespace: tenant-a
spec:
  vpc: tenant-a
  type: l3vpn
---
# Ethernet network
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: ew-network
  namespace: tenant-a
spec:
  vpc: tenant-a-ewf
  type: l3vpn
---
# Will create VPCPrefixes in NICO and corresponding Subnets in UFO

apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: ns-subnet
  namespace: tenant-a
spec:
  vpc: tenant-a
  network: ns-network
  prefix_length: 27
  subnetpool: default
  subnet: ns-subnet
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetAllocation
metadata:
  name: public-subnet
  namespace: tenant-a
spec:
  vpc: tenant-a
  network: public-network
  prefix_length: 29
  subnetpool: public
  subnet: public-subnet
---
apiVersion: ufo.mirantis.com/v1alpha1
kind: Subnet
metadata:
  name: ew-subnet
  namespace: tenant-a
spec:
  vpc: tenant-a-ewf
  network: ew-network
  cidr: 10.0.0.0/8
  addressAllocator:
    backend: rail-optimised
    gpuPlatform: B200
---
# NVLink partition network
apiVersion: ufo.mirantis.com/v1alpha1
kind: Network
metadata:
  name: nvlink-partition
  namespace: tenant-a
spec:
  vpc: tenant-a
  type: nvlink
