# NetworkBundle for NICO backend.
apiVersion: ufo.mirantis.com/v1alpha1
kind: NetworkBundle
metadata:
  name: tenant-a-networkbundle
  namespace: tenant-a
spec:
  clusterName: tenant-a-cluster
  networkv2:
    ethernets:
      enp1s0:
        dhcp4: true
        connectToNetwork:
          name: ns-network
    nvlinks:
      nvlink1:
        connectToNetwork:
          name: nvlink-partition
