apiVersion: ufo.mirantis.com/v1alpha1
kind: SubnetPoolAllocation
metadata:
  name: global-default-tenant-a
  namespace: kcm-system
spec:
  ip_version: 4
  prefix_length: 27
  source:
    subnetpool:
      name:  global-default
  target:
    subnetpool:
      name: default
      namespace: tenant-a
      max_prefix: 27
      min_prefix: 27
