apiVersion: v1
data:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
type: Opaque
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
spec:
  rootPasswordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-root-password
  database: {{ .Values.mariadb.auth.database }}
  storage:
    size: {{ .Values.mariadb.storage.size | default "10Gi" }}
  image: docker-registry1.mariadb.com/library/mariadb:10.11.16
  replicas: {{ .Values.mariadb.replicas | default 3 }}
  {{- if gt (int (.Values.mariadb.replicas | default 3)) 1 }}
  replication:
    enabled: true
    syncBinlog: 1
  {{- end }}
  myCnf: |
    [mariadb]
    event_scheduler=ON
    max_connections=1500
    log_bin_trust_function_creators=1
    innodb_log_file_size = 256M
    innodb_buffer_pool_size = 2G
    tmp_table_size = 256MB
    max_heap_table_size = 256MB
    query_cache_type = ON
    query_cache_size = 128M
    query_cache_limit = 4M
    thread_cache_size = 512
    table_open_cache = 8000
    table_definition_cache = 2000
    join_buffer_size = 8M
    sort_buffer_size = 2M
    read_buffer_size = 2M
  myCnfConfigMapKeyRef:
    name: mariadb
    key: my.cnf
  maxScaleRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha-user-all" }}
spec:
  database: {{ .Values.mariadb.auth.database }}
  grantOption: false
  host: '%'
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  privileges:
  - ALL PRIVILEGES
  table: '*'
  username: {{ .Values.mariadb.auth.username }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha-user" }}
spec:
  host: '%'
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  maxUserConnections: 1400
  name: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    key: mariadb-password
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
spec:
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  replicas: {{ .Values.maxscale.replicas | default 3 }}
  services:
  - listener:
      name: rw-router-listener
      port: 3306
      protocol: MariaDBProtocol
      suspend: false
    name: rw-router
    params:
      master_accept_reads: "true"
      transaction_replay: "true"
      max_replication_lag: "2s"
    router: readwritesplit
    suspend: false
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-00-xcaas
spec:
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 00-xcaas.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-01-tenants
spec:
  dependsOn:
    - name: netris-controller-initdb-00-xcaas
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 01-tenants.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-01-users
spec:
  dependsOn:
    - name: netris-controller-initdb-01-tenants
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 01-users.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-02-permissions
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 02-permissions.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-02-port
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 02-port.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-02-vpc
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 02-vpc.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-03-global-settings
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 03-global_settings.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-04-currency
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 04-currency.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-04-whitelist
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 04-whitelist.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-05-auth-schemes
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 05-auth_schemes.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-05-supported-platforms
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 05-supported_platforms.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-06-mon-thresholds
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 06-mon_thresholds.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-06-nos-list
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 06-nos_list.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-06-roh-profiles
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 06-roh_profiles.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-07-inventory-profiles
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 07-inventory_profiles.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-07-vpn-scores
spec:
  dependsOn:
    - name: netris-controller-initdb-01-users
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 07-vpn_scores.sql
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: netris-controller-initdb-09-dhcp-option-set
spec:
  dependsOn:
    - name: netris-controller-initdb-07-vpn-scores
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb-ha" }}
  username: {{ .Values.mariadb.auth.username }}
  passwordSecretKeyRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "mariadb" }}
    key: mariadb-password
  database: {{ .Values.mariadb.auth.database }}
  sqlConfigMapKeyRef:
    name: netris-controller-initdb
    key: 09-dhcp-option-set.sql
{{- $dot := . }}
{{- range $index := until (int ($dot.Values.mariadb.backupCount | default 3)) }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: {{ printf "%s-%s%d" (include "netris-controller.fullname" $dot) "mariadb-backup" (add1 $index) }}
spec:
  mariaDbRef:
    name: {{ printf "%s-%s" (include "netris-controller.fullname" $dot) "mariadb-ha" }}
  databases:
    - {{ $dot.Values.mariadb.auth.database }}
  schedule:
    cron: "0 */12 * * *"
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 20Gi
      accessModes:
        - ReadWriteOnce
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: mariadb-backup
        topologyKey: kubernetes.io/hostname
  podMetadata:
    labels:
      app: mariadb-backup
{{- end }}
