apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ntrs-grpc-tcp
spec:
  entryPoints:
    - ntrs-grpc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "grpc" }}
          port: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ntrs-teles-tcp
spec:
  entryPoints:
    - ntrs-teles
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "telescope" }}
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ntrs-teles-ssl-tcp
spec:
  entryPoints:
    - ntrs-teles-ssl
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "telescope" }}
          port: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ntrs-graphite-tcp
spec:
  entryPoints:
    - ntrs-graphite
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ printf "%s-vmc-vminsert" (include "netris-controller.fullname" .) }}
          port: 2003
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compress-middleware
spec:
  compress: {}
